/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package latihanKu;

/**
 *
 * @author ASUS
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonAufi = new javax.swing.JButton();
        buttonHelmy = new javax.swing.JButton();
        buttonWahyu = new javax.swing.JButton();
        buttonIsma = new javax.swing.JButton();
        buttonAnna = new javax.swing.JButton();
        buttonAura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIODATA TIM KELOMPOK 1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        buttonAufi.setBackground(new java.awt.Color(0, 51, 153));
        buttonAufi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonAufi.setForeground(new java.awt.Color(255, 255, 255));
        buttonAufi.setText("PROFIL AUFI ");
        buttonAufi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAufiActionPerformed(evt);
            }
        });

        buttonHelmy.setBackground(new java.awt.Color(0, 51, 153));
        buttonHelmy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonHelmy.setForeground(new java.awt.Color(255, 255, 255));
        buttonHelmy.setText("PROFIL HELMY ");
        buttonHelmy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHelmyActionPerformed(evt);
            }
        });

        buttonWahyu.setBackground(new java.awt.Color(0, 51, 153));
        buttonWahyu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonWahyu.setForeground(new java.awt.Color(255, 255, 255));
        buttonWahyu.setText("PROFIL WAHYU ");
        buttonWahyu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWahyuActionPerformed(evt);
            }
        });

        buttonIsma.setBackground(new java.awt.Color(0, 51, 153));
        buttonIsma.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonIsma.setForeground(new java.awt.Color(255, 255, 255));
        buttonIsma.setText("PROFIL ISMA ");
        buttonIsma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIsmaActionPerformed(evt);
            }
        });

        buttonAnna.setBackground(new java.awt.Color(0, 51, 153));
        buttonAnna.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonAnna.setForeground(new java.awt.Color(255, 255, 255));
        buttonAnna.setText("PROFIL ANNA ");
        buttonAnna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnnaActionPerformed(evt);
            }
        });

        buttonAura.setBackground(new java.awt.Color(0, 51, 153));
        buttonAura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonAura.setForeground(new java.awt.Color(255, 255, 255));
        buttonAura.setText("PROFIL AURA ");
        buttonAura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAuraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAufi, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonIsma, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonHelmy, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAnna, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAura, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonWahyu, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAufi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonHelmy, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonWahyu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonIsma, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAnna, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAura, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAufiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAufiActionPerformed
        // TODO add your handling code here:
        dispose();
        new aufiFrame().setVisible(true);
    }//GEN-LAST:event_buttonAufiActionPerformed

    private void buttonHelmyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHelmyActionPerformed
        // TODO add your handling code here:
        dispose();
        new HelmyFrem().setVisible(true);
    }//GEN-LAST:event_buttonHelmyActionPerformed

    private void buttonWahyuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWahyuActionPerformed
        // TODO add your handling code here:
        dispose();
        new wahyuframe().setVisible(true);
    }//GEN-LAST:event_buttonWahyuActionPerformed

    private void buttonIsmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIsmaActionPerformed
        // TODO add your handling code here:
        dispose();
        new IsmaFrame().setVisible(true);
    }//GEN-LAST:event_buttonIsmaActionPerformed

    private void buttonAnnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnnaActionPerformed
        // TODO add your handling code here:
        dispose();
        new ayaFrame().setVisible(true);
    }//GEN-LAST:event_buttonAnnaActionPerformed

    private void buttonAuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAuraActionPerformed
        // TODO add your handling code here:
        dispose();
        new auraa_frame().setVisible(true);
    }//GEN-LAST:event_buttonAuraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAnna;
    private javax.swing.JButton buttonAufi;
    private javax.swing.JButton buttonAura;
    private javax.swing.JButton buttonHelmy;
    private javax.swing.JButton buttonIsma;
    private javax.swing.JButton buttonWahyu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
